linters:
  enable:
    - bodyclose
    - errorlint
    - copyloopvar
    - gci
    - gocritic
    - gofmt
    - gosec
    - makezero
    - nilerr
    - noctx
    - sqlclosecheck
    - stylecheck
    - unconvert
    - spancheck
  disable:
    - errcheck
run:
  timeout: 10m
  build-tags:
    - test
