version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic
    - gomodguard
    - gosec
    - makezero
    - nilerr
    - noctx
    - spancheck
    - sqlclosecheck
    - staticcheck
    - unconvert
  disable:
    - errcheck
  settings:
    gomodguard:
      blocked:
        versions:
          - google.golang.org/grpc:
              version: '>1.58.3, <1.68.0'
              reason: 'gRPC may trigger a bug in xDS server: https://github.com/wongnai/xds/issues/11 . When using gRPC newer than 1.58.3, grpclib 1.18.0 must be used for a workaround'
          - go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc:
              version: <0.46.0
              reason: 'otelgrpc <0.46.0 provide high cardinality metrics: https://github.com/open-telemetry/opentelemetry-go-contrib/security/advisories/GHSA-8pgv-569h-w5rw'
    staticcheck:
      # Default value: https://staticcheck.dev/docs/configuration/options/#checks
      # QF1008: https://github.com/dominikh/go-tools/issues/1682
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-QF1008"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  build-tags:
    - test