// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/wongnai/xds/debug"
	"google.golang.org/grpc"
	"k8s.io/client-go/kubernetes"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context, statsIntervalSeconds StatsIntervalSeconds) (Servers, func(), error) {
	v := ProvideOtelGrpcServerOptions()
	server, cleanup := ProvideGrpcServer(v)
	config, err := ProvideClientConfig()
	if err != nil {
		cleanup()
		return Servers{}, nil, err
	}
	v2, err := ProvideK8sHTTPTransport(config)
	if err != nil {
		cleanup()
		return Servers{}, nil, err
	}
	v3 := ProvideK8sHTTPClient(v2, config)
	kubernetesInterface, err := ProvideK8sClient(config, v3)
	if err != nil {
		cleanup()
		return Servers{}, nil, err
	}
	snapshotter, cleanup2 := ProvideSnapshotter(ctx, kubernetesInterface)
	callbackFuncs := ProvideXdsLogger()
	serverServer, cleanup3 := ProvideXdsServer(ctx, snapshotter, callbackFuncs)
	sideEffectADSRegistered := ProvideSideEffectADSRegistered(server, serverServer)
	sideEffectEDSRegistered := ProvideSideEffectEDSRegistered(server, serverServer)
	sideEffectCDSRegistered := ProvideSideEffectCDSRegistered(server, serverServer)
	sideEffectRDSRegistered := ProvideSideEffectRDSRegistered(server, serverServer)
	sideEffectLDSRegistered := ProvideSideEffectLDSRegistered(server, serverServer)
	loadReportingServiceServer := ProvideLRSServer(statsIntervalSeconds)
	sideEffectLRSRegistered := ProvideSideEffectLRSRegistered(server, loadReportingServiceServer)
	xdsAllSideEffects := XdsAllSideEffects{
		_ADS: sideEffectADSRegistered,
		_EDS: sideEffectEDSRegistered,
		_CDS: sideEffectCDSRegistered,
		_RDS: sideEffectRDSRegistered,
		_LDS: sideEffectLDSRegistered,
		_LRS: sideEffectLRSRegistered,
	}
	devServer := DevServer{
		_Xds:       xdsAllSideEffects,
		GrpcServer: server,
	}
	healthServer, cleanup4 := ProvideGrpcHealthServer()
	sideEffectGrpcHealthRegistered := ProvideSideEffectGrpcHealthRegistered(server, healthServer)
	sideEffectGrpcReflectionRegistered := ProvideSideEffectGrpcReflectionRegisteredIfEnv(server)
	sideEffectGrpcChannelzRegistered := ProvideSideEffectGrpcChannelzRegistered(server)
	debugServer := ProvideDebugServer(snapshotter)
	servers := Servers{
		DevServer:   devServer,
		_GrpcHealth: sideEffectGrpcHealthRegistered,
		_Reflection: sideEffectGrpcReflectionRegistered,
		_Channelz:   sideEffectGrpcChannelzRegistered,
		DebugServer: debugServer,
	}
	return servers, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitializeTestServer(ctx context.Context, kubeClient kubernetes.Interface, statsIntervalSeconds StatsIntervalSeconds) (TestServer, func(), error) {
	v := ProvideGrpcTestOption()
	server, cleanup := ProvideGrpcServer(v)
	snapshotter, cleanup2 := ProvideSnapshotter(ctx, kubeClient)
	callbackFuncs := ProvideXdsLogger()
	serverServer, cleanup3 := ProvideXdsServer(ctx, snapshotter, callbackFuncs)
	sideEffectADSRegistered := ProvideSideEffectADSRegistered(server, serverServer)
	sideEffectEDSRegistered := ProvideSideEffectEDSRegistered(server, serverServer)
	sideEffectCDSRegistered := ProvideSideEffectCDSRegistered(server, serverServer)
	sideEffectRDSRegistered := ProvideSideEffectRDSRegistered(server, serverServer)
	sideEffectLDSRegistered := ProvideSideEffectLDSRegistered(server, serverServer)
	loadReportingServiceServer := ProvideLRSServer(statsIntervalSeconds)
	sideEffectLRSRegistered := ProvideSideEffectLRSRegistered(server, loadReportingServiceServer)
	xdsAllSideEffects := XdsAllSideEffects{
		_ADS: sideEffectADSRegistered,
		_EDS: sideEffectEDSRegistered,
		_CDS: sideEffectCDSRegistered,
		_RDS: sideEffectRDSRegistered,
		_LDS: sideEffectLDSRegistered,
		_LRS: sideEffectLRSRegistered,
	}
	devServer := DevServer{
		_Xds:       xdsAllSideEffects,
		GrpcServer: server,
	}
	testServer := TestServer{
		DevServer: devServer,
		Server:    serverServer,
	}
	return testServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type Servers struct {
	DevServer

	_GrpcHealth SideEffectGrpcHealthRegistered
	_Reflection SideEffectGrpcReflectionRegistered
	_Channelz   SideEffectGrpcChannelzRegistered

	DebugServer *debug.Server
}

type DevServer struct {
	_Xds       XdsAllSideEffects
	GrpcServer *grpc.Server
}
